### ISSUE TITLE
안녕하세요 vue-native로 앱을만드는중인데요

### ISSUE THREAD

**Issue by lavy1004** [iamport/iamport-vue-native#3]
vue native에서 chart.js와 같은 라이브러리 사용방법을 아는 분이계실까요

vue native 자료찾고싶습니다 도와주세요 ㅠ

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

react native 모듈을 vue native에서도 사용할 수 있으니,
react native용 라이브러리로 찾아보심이 어떨까요?

올려주신 이슈는 아임포트 모듈과 관계가 없으니 close 하도록 하겠습니다.
감사합니다.
